apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: echo-server
  namespace: echo-server
spec:
  interval: 5m
  releaseName: echo-server
  targetNamespace: echo-server 
  chart:
    spec:
      chart: ./apps/echo-server
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: false
  upgrade:
    remediation:
      remediateLastFailure: true
  valuesFrom:
    - kind: ConfigMap
      name: echo-server-values
      valuesKey: values.yaml
